// Pre-filled templates for common services and tools
export interface ServiceTemplate {
  name: string;
  vendor: string;
  category: string;
  icon: string;
  description: string;
  features: string;
  url: string;
  login_url: string;
  is_paid: boolean;
  billing_cycle?: string;
  license_type?: string;
}

export const serviceTemplates: ServiceTemplate[] = [
  // ============ AWS Services ============
  {
    name: 'AWS Lambda',
    vendor: 'Amazon Web Services',
    category: 'infrastructure',
    icon: '⚡',
    description: 'Serverless compute service that runs code in response to events and automatically manages compute resources.',
    features: 'Serverless, Auto-scaling, Pay-per-use, Multiple runtimes, Event-driven, VPC support',
    url: 'https://aws.amazon.com/lambda/',
    login_url: 'https://console.aws.amazon.com/lambda/',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },
  {
    name: 'AWS EC2',
    vendor: 'Amazon Web Services',
    category: 'infrastructure',
    icon: '🖥️',
    description: 'Elastic Compute Cloud - scalable virtual servers in the cloud for running applications.',
    features: 'Virtual servers, Auto-scaling, Multiple instance types, Spot instances, Reserved capacity, EBS storage',
    url: 'https://aws.amazon.com/ec2/',
    login_url: 'https://console.aws.amazon.com/ec2/',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },
  {
    name: 'AWS Lightsail',
    vendor: 'Amazon Web Services',
    category: 'infrastructure',
    icon: '💡',
    description: 'Simple virtual private servers with predictable pricing for small-scale applications and websites.',
    features: 'Fixed pricing, SSD storage, Static IPs, DNS management, Snapshots, Load balancers',
    url: 'https://aws.amazon.com/lightsail/',
    login_url: 'https://lightsail.aws.amazon.com/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'starter',
  },
  {
    name: 'AWS S3',
    vendor: 'Amazon Web Services',
    category: 'infrastructure',
    icon: '🪣',
    description: 'Simple Storage Service - scalable object storage for data backup, archival, and analytics.',
    features: 'Object storage, Versioning, Lifecycle policies, Cross-region replication, Static hosting, Glacier integration',
    url: 'https://aws.amazon.com/s3/',
    login_url: 'https://console.aws.amazon.com/s3/',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },
  {
    name: 'AWS RDS',
    vendor: 'Amazon Web Services',
    category: 'infrastructure',
    icon: '🗄️',
    description: 'Relational Database Service - managed database service for MySQL, PostgreSQL, MariaDB, Oracle, and SQL Server.',
    features: 'Managed databases, Auto backups, Multi-AZ, Read replicas, Auto scaling, Performance insights',
    url: 'https://aws.amazon.com/rds/',
    login_url: 'https://console.aws.amazon.com/rds/',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },
  {
    name: 'AWS CloudFront',
    vendor: 'Amazon Web Services',
    category: 'infrastructure',
    icon: '🌐',
    description: 'Content delivery network (CDN) for fast, secure delivery of websites, APIs, and streaming content.',
    features: 'Global CDN, Edge locations, SSL/TLS, DDoS protection, Lambda@Edge, Real-time logs',
    url: 'https://aws.amazon.com/cloudfront/',
    login_url: 'https://console.aws.amazon.com/cloudfront/',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },
  {
    name: 'AWS Route 53',
    vendor: 'Amazon Web Services',
    category: 'infrastructure',
    icon: '🗺️',
    description: 'Scalable DNS and domain registration service with health checking and traffic routing.',
    features: 'DNS management, Domain registration, Health checks, Traffic routing, DNSSEC, Private DNS',
    url: 'https://aws.amazon.com/route53/',
    login_url: 'https://console.aws.amazon.com/route53/',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },
  {
    name: 'AWS SES',
    vendor: 'Amazon Web Services',
    category: 'communication',
    icon: '📧',
    description: 'Simple Email Service - scalable email sending and receiving service for transactional and marketing emails.',
    features: 'Transactional email, Bulk sending, Email receiving, Templates, Analytics, Deliverability tools',
    url: 'https://aws.amazon.com/ses/',
    login_url: 'https://console.aws.amazon.com/ses/',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },

  // ============ Azure Services ============
  {
    name: 'Azure Functions',
    vendor: 'Microsoft Azure',
    category: 'infrastructure',
    icon: '⚡',
    description: 'Serverless compute service for running event-driven code without managing infrastructure.',
    features: 'Serverless, Multiple triggers, Durable functions, Premium plan, VNET integration, Bindings',
    url: 'https://azure.microsoft.com/en-us/products/functions/',
    login_url: 'https://portal.azure.com/#blade/HubsExtension/BrowseResource/resourceType/Microsoft.Web%2Fsites/kind/functionapp',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },
  {
    name: 'Azure Virtual Machines',
    vendor: 'Microsoft Azure',
    category: 'infrastructure',
    icon: '🖥️',
    description: 'Scalable on-demand virtualized computing resources in the Azure cloud.',
    features: 'Windows/Linux VMs, Scale sets, Spot VMs, Reserved instances, Hybrid benefit, Managed disks',
    url: 'https://azure.microsoft.com/en-us/products/virtual-machines/',
    login_url: 'https://portal.azure.com/#blade/HubsExtension/BrowseResource/resourceType/Microsoft.Compute%2FVirtualMachines',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },
  {
    name: 'Azure Blob Storage',
    vendor: 'Microsoft Azure',
    category: 'infrastructure',
    icon: '🪣',
    description: 'Massively scalable object storage for unstructured data like documents, images, and videos.',
    features: 'Object storage, Hot/Cool/Archive tiers, Versioning, Lifecycle management, Static hosting, CDN integration',
    url: 'https://azure.microsoft.com/en-us/products/storage/blobs/',
    login_url: 'https://portal.azure.com/#blade/HubsExtension/BrowseResource/resourceType/Microsoft.Storage%2FStorageAccounts',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },
  {
    name: 'Azure App Service',
    vendor: 'Microsoft Azure',
    category: 'infrastructure',
    icon: '🚀',
    description: 'Fully managed platform for building, deploying, and scaling web apps and APIs.',
    features: 'PaaS hosting, Auto-scaling, Deployment slots, Custom domains, SSL certificates, CI/CD integration',
    url: 'https://azure.microsoft.com/en-us/products/app-service/',
    login_url: 'https://portal.azure.com/#blade/HubsExtension/BrowseResource/resourceType/Microsoft.Web%2Fsites',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'custom',
  },
  {
    name: 'Azure SQL Database',
    vendor: 'Microsoft Azure',
    category: 'infrastructure',
    icon: '🗄️',
    description: 'Fully managed relational database service with built-in intelligence and security.',
    features: 'Managed SQL Server, Auto-tuning, Geo-replication, Serverless option, Hyperscale, Advanced security',
    url: 'https://azure.microsoft.com/en-us/products/azure-sql/database/',
    login_url: 'https://portal.azure.com/#blade/HubsExtension/BrowseResource/resourceType/Microsoft.Sql%2Fservers%2Fdatabases',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },
  {
    name: 'Azure DevOps',
    vendor: 'Microsoft Azure',
    category: 'development',
    icon: '🔄',
    description: 'Development collaboration tools including repos, pipelines, boards, and artifacts.',
    features: 'Git repos, CI/CD pipelines, Kanban boards, Test plans, Artifacts, Wiki',
    url: 'https://azure.microsoft.com/en-us/products/devops/',
    login_url: 'https://dev.azure.com/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },

  // ============ Google Cloud Services ============
  {
    name: 'Google Cloud Compute Engine',
    vendor: 'Google Cloud',
    category: 'infrastructure',
    icon: '🖥️',
    description: 'Scalable, high-performance virtual machines running in Google data centers.',
    features: 'Custom machine types, Preemptible VMs, Live migration, Persistent disks, GPU support, Sole-tenant nodes',
    url: 'https://cloud.google.com/compute',
    login_url: 'https://console.cloud.google.com/compute/instances',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },
  {
    name: 'Google Cloud Functions',
    vendor: 'Google Cloud',
    category: 'infrastructure',
    icon: '⚡',
    description: 'Serverless execution environment for building and connecting cloud services.',
    features: 'Serverless, Event-driven, Auto-scaling, Multiple runtimes, VPC connector, Cloud events',
    url: 'https://cloud.google.com/functions',
    login_url: 'https://console.cloud.google.com/functions',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },
  {
    name: 'Google Cloud Storage',
    vendor: 'Google Cloud',
    category: 'infrastructure',
    icon: '🪣',
    description: 'Unified object storage for developers and enterprises with global edge-caching.',
    features: 'Object storage, Multi-regional, Lifecycle management, Versioning, Strong consistency, CDN integration',
    url: 'https://cloud.google.com/storage',
    login_url: 'https://console.cloud.google.com/storage/browser',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },
  {
    name: 'Google Cloud Run',
    vendor: 'Google Cloud',
    category: 'infrastructure',
    icon: '🏃',
    description: 'Fully managed compute platform for running containerized applications.',
    features: 'Container hosting, Auto-scaling, Pay-per-use, Custom domains, Traffic splitting, Knative-based',
    url: 'https://cloud.google.com/run',
    login_url: 'https://console.cloud.google.com/run',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },
  {
    name: 'Firebase',
    vendor: 'Google',
    category: 'infrastructure',
    icon: '🔥',
    description: 'Platform for building mobile and web applications with real-time database and authentication.',
    features: 'Real-time database, Authentication, Cloud functions, Hosting, Analytics, Crashlytics',
    url: 'https://firebase.google.com/',
    login_url: 'https://console.firebase.google.com/',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'freemium',
  },

  // ============ Domain Registrars ============
  {
    name: 'Namecheap',
    vendor: 'Namecheap',
    category: 'infrastructure',
    icon: '🌐',
    description: 'Domain registrar and web hosting provider with competitive pricing and free privacy protection.',
    features: 'Domain registration, Free WHOIS privacy, DNS management, SSL certificates, Email hosting, Web hosting',
    url: 'https://www.namecheap.com/',
    login_url: 'https://www.namecheap.com/myaccount/login/',
    is_paid: true,
    billing_cycle: 'annually',
    license_type: 'custom',
  },
  {
    name: 'GoDaddy',
    vendor: 'GoDaddy',
    category: 'infrastructure',
    icon: '🌐',
    description: 'World\'s largest domain registrar with web hosting, website builder, and marketing tools.',
    features: 'Domain registration, Web hosting, Website builder, Email, SSL certificates, Marketing tools',
    url: 'https://www.godaddy.com/',
    login_url: 'https://sso.godaddy.com/',
    is_paid: true,
    billing_cycle: 'annually',
    license_type: 'custom',
  },
  {
    name: 'Cloudflare',
    vendor: 'Cloudflare',
    category: 'infrastructure',
    icon: '☁️',
    description: 'Web performance and security company providing CDN, DNS, DDoS protection, and domain registration.',
    features: 'CDN, DNS, DDoS protection, WAF, SSL/TLS, Workers, Pages, Domain registration, Zero Trust',
    url: 'https://www.cloudflare.com/',
    login_url: 'https://dash.cloudflare.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Google Domains',
    vendor: 'Google (now Squarespace)',
    category: 'infrastructure',
    icon: '🌐',
    description: 'Domain registration service with simple management and Google integration (now part of Squarespace).',
    features: 'Domain registration, DNS management, Email forwarding, WHOIS privacy, Google integration',
    url: 'https://domains.squarespace.com/',
    login_url: 'https://domains.squarespace.com/',
    is_paid: true,
    billing_cycle: 'annually',
    license_type: 'custom',
  },
  {
    name: 'Hover',
    vendor: 'Hover',
    category: 'infrastructure',
    icon: '🌐',
    description: 'Simple, no-upsell domain registration with free WHOIS privacy and email forwarding.',
    features: 'Domain registration, Free WHOIS privacy, Email forwarding, DNS management, Simple interface',
    url: 'https://www.hover.com/',
    login_url: 'https://www.hover.com/signin',
    is_paid: true,
    billing_cycle: 'annually',
    license_type: 'custom',
  },

  // ============ Hosting Platforms ============
  {
    name: 'Vercel',
    vendor: 'Vercel',
    category: 'infrastructure',
    icon: '▲',
    description: 'Platform for frontend frameworks and static sites with automatic deployments from Git.',
    features: 'Instant deployments, Preview URLs, Serverless functions, Edge network, Analytics, Next.js optimized',
    url: 'https://vercel.com/',
    login_url: 'https://vercel.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Netlify',
    vendor: 'Netlify',
    category: 'infrastructure',
    icon: '🔷',
    description: 'Platform for automating modern web projects with continuous deployment and serverless functions.',
    features: 'Continuous deployment, Serverless functions, Forms, Identity, Split testing, Edge handlers',
    url: 'https://www.netlify.com/',
    login_url: 'https://app.netlify.com/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Heroku',
    vendor: 'Salesforce',
    category: 'infrastructure',
    icon: '🟣',
    description: 'Cloud platform as a service supporting multiple programming languages for app deployment.',
    features: 'PaaS hosting, Dynos, Add-ons marketplace, Pipelines, Review apps, Postgres, Redis',
    url: 'https://www.heroku.com/',
    login_url: 'https://id.heroku.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'DigitalOcean',
    vendor: 'DigitalOcean',
    category: 'infrastructure',
    icon: '🌊',
    description: 'Cloud infrastructure provider with simple, predictable pricing for developers and businesses.',
    features: 'Droplets, Kubernetes, App Platform, Managed databases, Spaces, Load balancers, VPC',
    url: 'https://www.digitalocean.com/',
    login_url: 'https://cloud.digitalocean.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'custom',
  },
  {
    name: 'Railway',
    vendor: 'Railway',
    category: 'infrastructure',
    icon: '🚂',
    description: 'Modern deployment platform for building and shipping applications with instant infrastructure.',
    features: 'Instant deployments, Databases, Private networking, Environments, Usage-based pricing, Templates',
    url: 'https://railway.app/',
    login_url: 'https://railway.app/login',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'freemium',
  },
  {
    name: 'Render',
    vendor: 'Render',
    category: 'infrastructure',
    icon: '🎨',
    description: 'Unified cloud to build and run all your apps and websites with free SSL and a global CDN.',
    features: 'Web services, Static sites, Cron jobs, Databases, Redis, Private services, Auto-deploy',
    url: 'https://render.com/',
    login_url: 'https://dashboard.render.com/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },

  // ============ Development Tools ============
  {
    name: 'GitHub',
    vendor: 'Microsoft',
    category: 'development',
    icon: '🐙',
    description: 'Web-based platform for version control and collaboration using Git repositories.',
    features: 'Git hosting, Pull requests, Issues, Actions CI/CD, Codespaces, Copilot, Packages, Security',
    url: 'https://github.com/',
    login_url: 'https://github.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'GitLab',
    vendor: 'GitLab',
    category: 'development',
    icon: '🦊',
    description: 'Complete DevOps platform with source control, CI/CD, security, and project management.',
    features: 'Git hosting, CI/CD pipelines, Issue tracking, Code review, Security scanning, Container registry',
    url: 'https://gitlab.com/',
    login_url: 'https://gitlab.com/users/sign_in',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Bitbucket',
    vendor: 'Atlassian',
    category: 'development',
    icon: '🪣',
    description: 'Git repository management solution with Jira and Trello integration.',
    features: 'Git hosting, Pipelines CI/CD, Pull requests, Code review, Jira integration, Trello integration',
    url: 'https://bitbucket.org/',
    login_url: 'https://bitbucket.org/account/signin/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Docker Hub',
    vendor: 'Docker',
    category: 'development',
    icon: '🐳',
    description: 'Container image registry for storing, sharing, and managing Docker container images.',
    features: 'Container registry, Official images, Automated builds, Webhooks, Teams, Vulnerability scanning',
    url: 'https://hub.docker.com/',
    login_url: 'https://login.docker.com/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'npm',
    vendor: 'GitHub/Microsoft',
    category: 'development',
    icon: '📦',
    description: 'Package manager for JavaScript and the world\'s largest software registry.',
    features: 'Package hosting, Private packages, Teams, Security advisories, Provenance, Workspaces',
    url: 'https://www.npmjs.com/',
    login_url: 'https://www.npmjs.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'JetBrains',
    vendor: 'JetBrains',
    category: 'development',
    icon: '🧠',
    description: 'Professional IDE suite including IntelliJ IDEA, PyCharm, WebStorm, and more.',
    features: 'Smart code completion, Refactoring, Debugging, Version control, Database tools, AI assistant',
    url: 'https://www.jetbrains.com/',
    login_url: 'https://account.jetbrains.com/login',
    is_paid: true,
    billing_cycle: 'annually',
    license_type: 'pro',
  },
  {
    name: 'Postman',
    vendor: 'Postman',
    category: 'development',
    icon: '🚀',
    description: 'API platform for building, testing, documenting, and sharing APIs.',
    features: 'API testing, Collections, Environments, Mock servers, Documentation, Monitors, Flows',
    url: 'https://www.postman.com/',
    login_url: 'https://identity.getpostman.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },

  // ============ Communication ============
  {
    name: 'Slack',
    vendor: 'Salesforce',
    category: 'communication',
    icon: '💬',
    description: 'Business communication platform with channels, direct messaging, and app integrations.',
    features: 'Channels, Direct messages, Threads, File sharing, App integrations, Huddles, Workflows',
    url: 'https://slack.com/',
    login_url: 'https://slack.com/signin',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Discord',
    vendor: 'Discord',
    category: 'communication',
    icon: '🎮',
    description: 'Voice, video, and text communication platform originally for gamers, now used by communities.',
    features: 'Voice channels, Text channels, Screen sharing, Bots, Roles, Server templates, Stage channels',
    url: 'https://discord.com/',
    login_url: 'https://discord.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Microsoft Teams',
    vendor: 'Microsoft',
    category: 'communication',
    icon: '👥',
    description: 'Business communication and collaboration platform integrated with Microsoft 365.',
    features: 'Chat, Video calls, File sharing, Channels, Apps, Meetings, Webinars, Office integration',
    url: 'https://www.microsoft.com/en-us/microsoft-teams/',
    login_url: 'https://teams.microsoft.com/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Zoom',
    vendor: 'Zoom',
    category: 'communication',
    icon: '📹',
    description: 'Video conferencing platform for meetings, webinars, and virtual events.',
    features: 'Video meetings, Webinars, Chat, Phone, Whiteboard, Breakout rooms, Recording, Virtual backgrounds',
    url: 'https://zoom.us/',
    login_url: 'https://zoom.us/signin',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Google Meet',
    vendor: 'Google',
    category: 'communication',
    icon: '📹',
    description: 'Video conferencing service integrated with Google Workspace.',
    features: 'Video meetings, Screen sharing, Live captions, Recording, Breakout rooms, Q&A, Polls',
    url: 'https://meet.google.com/',
    login_url: 'https://meet.google.com/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },

  // ============ Email Services ============
  {
    name: 'Google Workspace',
    vendor: 'Google',
    category: 'communication',
    icon: '📧',
    description: 'Business productivity suite with Gmail, Drive, Docs, Calendar, and Meet.',
    features: 'Business email, Cloud storage, Docs/Sheets/Slides, Calendar, Meet, Admin console, Vault',
    url: 'https://workspace.google.com/',
    login_url: 'https://admin.google.com/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'business',
  },
  {
    name: 'Microsoft 365',
    vendor: 'Microsoft',
    category: 'productivity',
    icon: '📧',
    description: 'Business productivity suite with Outlook, OneDrive, Word, Excel, and Teams.',
    features: 'Business email, OneDrive, Word/Excel/PowerPoint, Teams, SharePoint, Admin center, Security',
    url: 'https://www.microsoft.com/en-us/microsoft-365/business/',
    login_url: 'https://admin.microsoft.com/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'business',
  },
  {
    name: 'SendGrid',
    vendor: 'Twilio',
    category: 'communication',
    icon: '📨',
    description: 'Cloud-based email delivery platform for transactional and marketing emails.',
    features: 'Email API, SMTP relay, Marketing campaigns, Templates, Analytics, Deliverability tools',
    url: 'https://sendgrid.com/',
    login_url: 'https://app.sendgrid.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Mailgun',
    vendor: 'Sinch',
    category: 'communication',
    icon: '📬',
    description: 'Email API service for sending, receiving, and tracking transactional emails.',
    features: 'Email API, SMTP, Inbound routing, Email validation, Analytics, Webhooks',
    url: 'https://www.mailgun.com/',
    login_url: 'https://login.mailgun.com/login/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Resend',
    vendor: 'Resend',
    category: 'communication',
    icon: '✉️',
    description: 'Modern email API for developers with React Email support and excellent deliverability.',
    features: 'Email API, React Email, Webhooks, Analytics, Team management, Multiple domains',
    url: 'https://resend.com/',
    login_url: 'https://resend.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Postmark',
    vendor: 'ActiveCampaign',
    category: 'communication',
    icon: '📮',
    description: 'Transactional email service focused on deliverability and speed.',
    features: 'Transactional email, Templates, Message streams, Analytics, Webhooks, Inbound processing',
    url: 'https://postmarkapp.com/',
    login_url: 'https://account.postmarkapp.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'starter',
  },

  // ============ Productivity ============
  {
    name: 'Notion',
    vendor: 'Notion Labs',
    category: 'productivity',
    icon: '📝',
    description: 'All-in-one workspace for notes, docs, wikis, projects, and collaboration.',
    features: 'Notes, Docs, Wikis, Databases, Kanban, Calendar, Templates, API, AI assistant',
    url: 'https://www.notion.so/',
    login_url: 'https://www.notion.so/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Asana',
    vendor: 'Asana',
    category: 'productivity',
    icon: '✅',
    description: 'Work management platform for teams to organize, track, and manage work.',
    features: 'Tasks, Projects, Timeline, Boards, Portfolios, Goals, Automation, Reporting',
    url: 'https://asana.com/',
    login_url: 'https://app.asana.com/-/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Trello',
    vendor: 'Atlassian',
    category: 'productivity',
    icon: '📋',
    description: 'Visual collaboration tool using boards, lists, and cards for project management.',
    features: 'Boards, Lists, Cards, Power-Ups, Butler automation, Templates, Calendar view',
    url: 'https://trello.com/',
    login_url: 'https://trello.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Linear',
    vendor: 'Linear',
    category: 'productivity',
    icon: '📐',
    description: 'Modern issue tracking and project management tool built for software teams.',
    features: 'Issues, Cycles, Roadmaps, Projects, Triage, Git integration, Keyboard shortcuts, API',
    url: 'https://linear.app/',
    login_url: 'https://linear.app/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Jira',
    vendor: 'Atlassian',
    category: 'productivity',
    icon: '🔷',
    description: 'Issue and project tracking software for agile development teams.',
    features: 'Issues, Sprints, Kanban, Roadmaps, Reports, Automation, Integrations, Custom workflows',
    url: 'https://www.atlassian.com/software/jira',
    login_url: 'https://id.atlassian.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Monday.com',
    vendor: 'Monday.com',
    category: 'productivity',
    icon: '📊',
    description: 'Work operating system for managing projects, workflows, and team collaboration.',
    features: 'Boards, Dashboards, Automations, Integrations, Forms, Docs, Workload, Time tracking',
    url: 'https://monday.com/',
    login_url: 'https://auth.monday.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'starter',
  },
  {
    name: 'Confluence',
    vendor: 'Atlassian',
    category: 'productivity',
    icon: '📚',
    description: 'Team workspace for creating, organizing, and collaborating on documentation.',
    features: 'Pages, Spaces, Templates, Comments, Permissions, Macros, Jira integration, Search',
    url: 'https://www.atlassian.com/software/confluence',
    login_url: 'https://id.atlassian.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },

  // ============ Design ============
  {
    name: 'Figma',
    vendor: 'Figma (Adobe)',
    category: 'design',
    icon: '🎨',
    description: 'Collaborative interface design tool for creating UI/UX designs and prototypes.',
    features: 'Vector editing, Prototyping, Components, Auto layout, Plugins, Dev mode, FigJam',
    url: 'https://www.figma.com/',
    login_url: 'https://www.figma.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Canva',
    vendor: 'Canva',
    category: 'design',
    icon: '🖼️',
    description: 'Online graphic design platform with templates for social media, presentations, and more.',
    features: 'Templates, Brand kit, Magic resize, Background remover, Collaboration, Print, Video editor',
    url: 'https://www.canva.com/',
    login_url: 'https://www.canva.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Adobe Creative Cloud',
    vendor: 'Adobe',
    category: 'design',
    icon: '🎭',
    description: 'Suite of creative applications including Photoshop, Illustrator, Premiere Pro, and more.',
    features: 'Photoshop, Illustrator, Premiere Pro, After Effects, XD, Lightroom, Cloud storage, Fonts',
    url: 'https://www.adobe.com/creativecloud.html',
    login_url: 'https://account.adobe.com/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'pro',
  },

  // ============ Analytics ============
  {
    name: 'Google Analytics',
    vendor: 'Google',
    category: 'analytics',
    icon: '📈',
    description: 'Web analytics service tracking and reporting website traffic and user behavior.',
    features: 'Traffic analysis, Audience insights, Conversions, Real-time data, Custom reports, BigQuery export',
    url: 'https://analytics.google.com/',
    login_url: 'https://analytics.google.com/',
    is_paid: false,
    billing_cycle: '',
    license_type: 'free',
  },
  {
    name: 'Mixpanel',
    vendor: 'Mixpanel',
    category: 'analytics',
    icon: '📊',
    description: 'Product analytics platform for tracking user interactions and behavior.',
    features: 'Event tracking, Funnels, Retention, Cohorts, A/B testing, User profiles, Alerts',
    url: 'https://mixpanel.com/',
    login_url: 'https://mixpanel.com/login/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Amplitude',
    vendor: 'Amplitude',
    category: 'analytics',
    icon: '📉',
    description: 'Digital analytics platform for understanding user behavior and product growth.',
    features: 'Behavioral analytics, Cohorts, Funnels, Pathfinder, Experiments, Audiences, CDP',
    url: 'https://amplitude.com/',
    login_url: 'https://analytics.amplitude.com/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Hotjar',
    vendor: 'Contentsquare',
    category: 'analytics',
    icon: '🔥',
    description: 'Behavior analytics and feedback tool with heatmaps and session recordings.',
    features: 'Heatmaps, Session recordings, Surveys, Feedback widgets, Funnels, User interviews',
    url: 'https://www.hotjar.com/',
    login_url: 'https://insights.hotjar.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'PostHog',
    vendor: 'PostHog',
    category: 'analytics',
    icon: '🦔',
    description: 'Open-source product analytics platform with feature flags and session replay.',
    features: 'Event analytics, Session replay, Feature flags, A/B testing, Surveys, Data warehouse',
    url: 'https://posthog.com/',
    login_url: 'https://app.posthog.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },

  // ============ Payments ============
  {
    name: 'Stripe',
    vendor: 'Stripe',
    category: 'finance',
    icon: '💳',
    description: 'Online payment processing platform for internet businesses.',
    features: 'Payments, Subscriptions, Invoicing, Connect, Radar fraud, Terminal, Atlas, Tax',
    url: 'https://stripe.com/',
    login_url: 'https://dashboard.stripe.com/login',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },
  {
    name: 'PayPal',
    vendor: 'PayPal',
    category: 'finance',
    icon: '💰',
    description: 'Online payments system for sending and receiving money and accepting payments.',
    features: 'Payments, Invoicing, Pay Later, Business account, Mass payments, Subscriptions',
    url: 'https://www.paypal.com/',
    login_url: 'https://www.paypal.com/signin',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },
  {
    name: 'Square',
    vendor: 'Block',
    category: 'finance',
    icon: '⬜',
    description: 'Financial services and digital payments company with POS and online payments.',
    features: 'POS, Online payments, Invoicing, Payroll, Banking, Appointments, Loyalty',
    url: 'https://squareup.com/',
    login_url: 'https://squareup.com/login',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },

  // ============ Marketing ============
  {
    name: 'Mailchimp',
    vendor: 'Intuit',
    category: 'marketing',
    icon: '🐵',
    description: 'Marketing automation platform for email campaigns, landing pages, and audience management.',
    features: 'Email campaigns, Automations, Landing pages, Audience management, Analytics, A/B testing',
    url: 'https://mailchimp.com/',
    login_url: 'https://login.mailchimp.com/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'HubSpot',
    vendor: 'HubSpot',
    category: 'marketing',
    icon: '🧡',
    description: 'CRM platform with marketing, sales, service, and content management tools.',
    features: 'CRM, Marketing automation, Sales pipeline, Service desk, CMS, Analytics, AI',
    url: 'https://www.hubspot.com/',
    login_url: 'https://app.hubspot.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'ConvertKit',
    vendor: 'ConvertKit',
    category: 'marketing',
    icon: '✉️',
    description: 'Email marketing platform designed for creators with automations and landing pages.',
    features: 'Email sequences, Automations, Landing pages, Forms, Subscriber tagging, Commerce',
    url: 'https://convertkit.com/',
    login_url: 'https://app.convertkit.com/users/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },

  // ============ Security ============
  {
    name: '1Password',
    vendor: '1Password',
    category: 'security',
    icon: '🔐',
    description: 'Password manager for teams and families with secure credential sharing.',
    features: 'Password vault, Secure sharing, Watchtower, Travel mode, SSO, CLI, Browser extension',
    url: 'https://1password.com/',
    login_url: 'https://my.1password.com/signin',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'business',
  },
  {
    name: 'LastPass',
    vendor: 'LastPass',
    category: 'security',
    icon: '🔒',
    description: 'Password manager with secure vault, password generator, and team features.',
    features: 'Password vault, Auto-fill, Password generator, Secure notes, Dark web monitoring, SSO',
    url: 'https://www.lastpass.com/',
    login_url: 'https://lastpass.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Auth0',
    vendor: 'Okta',
    category: 'security',
    icon: '🛡️',
    description: 'Identity platform for authentication and authorization with universal login.',
    features: 'Universal login, SSO, MFA, Social login, User management, Rules, Actions',
    url: 'https://auth0.com/',
    login_url: 'https://manage.auth0.com/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'Okta',
    vendor: 'Okta',
    category: 'security',
    icon: '🔑',
    description: 'Enterprise identity and access management platform with SSO and MFA.',
    features: 'SSO, MFA, Lifecycle management, API access, Universal directory, Workflows',
    url: 'https://www.okta.com/',
    login_url: 'https://login.okta.com/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'enterprise',
  },

  // ============ Monitoring ============
  {
    name: 'Datadog',
    vendor: 'Datadog',
    category: 'analytics',
    icon: '🐕',
    description: 'Monitoring and analytics platform for cloud-scale applications and infrastructure.',
    features: 'Infrastructure monitoring, APM, Logs, RUM, Synthetics, Security, Dashboards',
    url: 'https://www.datadoghq.com/',
    login_url: 'https://app.datadoghq.com/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'custom',
  },
  {
    name: 'Sentry',
    vendor: 'Sentry',
    category: 'development',
    icon: '🐛',
    description: 'Application monitoring and error tracking platform for developers.',
    features: 'Error tracking, Performance monitoring, Session replay, Profiling, Crons, Releases',
    url: 'https://sentry.io/',
    login_url: 'https://sentry.io/auth/login/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'New Relic',
    vendor: 'New Relic',
    category: 'analytics',
    icon: '📊',
    description: 'Observability platform for monitoring applications, infrastructure, and logs.',
    features: 'APM, Infrastructure, Logs, Browser, Synthetics, Mobile, Alerts, Dashboards',
    url: 'https://newrelic.com/',
    login_url: 'https://login.newrelic.com/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
  {
    name: 'PagerDuty',
    vendor: 'PagerDuty',
    category: 'productivity',
    icon: '🚨',
    description: 'Incident management platform for real-time operations and on-call scheduling.',
    features: 'Incident response, On-call scheduling, Escalation policies, Integrations, Analytics, Automation',
    url: 'https://www.pagerduty.com/',
    login_url: 'https://app.pagerduty.com/',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'pro',
  },

  // ============ AI/ML ============
  {
    name: 'OpenAI',
    vendor: 'OpenAI',
    category: 'development',
    icon: '🤖',
    description: 'AI research company providing GPT models, DALL-E, and other AI APIs.',
    features: 'GPT-4, ChatGPT, DALL-E, Whisper, Embeddings, Fine-tuning, Assistants API',
    url: 'https://openai.com/',
    login_url: 'https://platform.openai.com/login',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },
  {
    name: 'Anthropic Claude',
    vendor: 'Anthropic',
    category: 'development',
    icon: '🧠',
    description: 'AI assistant and API providing Claude models for various AI applications.',
    features: 'Claude models, API access, Long context, Vision, Tool use, Constitutional AI',
    url: 'https://www.anthropic.com/',
    login_url: 'https://console.anthropic.com/',
    is_paid: true,
    billing_cycle: 'usage',
    license_type: 'custom',
  },
  {
    name: 'Hugging Face',
    vendor: 'Hugging Face',
    category: 'development',
    icon: '🤗',
    description: 'AI community platform with model hub, datasets, and inference endpoints.',
    features: 'Model hub, Datasets, Spaces, Inference API, AutoTrain, Transformers library',
    url: 'https://huggingface.co/',
    login_url: 'https://huggingface.co/login',
    is_paid: true,
    billing_cycle: 'monthly',
    license_type: 'freemium',
  },
];

// Group templates by category for easier browsing
export const templatesByCategory = serviceTemplates.reduce((acc, template) => {
  if (!acc[template.category]) {
    acc[template.category] = [];
  }
  acc[template.category].push(template);
  return acc;
}, {} as Record<string, ServiceTemplate[]>);

// Search templates
export const searchTemplates = (query: string): ServiceTemplate[] => {
  const lowerQuery = query.toLowerCase();
  return serviceTemplates.filter(t =>
    t.name.toLowerCase().includes(lowerQuery) ||
    t.vendor.toLowerCase().includes(lowerQuery) ||
    t.description.toLowerCase().includes(lowerQuery)
  );
};
